[build]
  command = "npm ci && npm run build"
  functions = "netlify/functions"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect rules for Next.js
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, X-API-Key"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Function configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Environment variables (these should be set in Netlify UI)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY
# UPSTASH_REDIS_REST_URL
# UPSTASH_REDIS_REST_TOKEN
# CLOUDFLARE_R2_ACCOUNT_ID
# CLOUDFLARE_R2_ACCESS_KEY_ID
# CLOUDFLARE_R2_SECRET_ACCESS_KEY
# CLOUDFLARE_R2_BUCKET_NAME
# CLOUDFLARE_R2_PUBLIC_URL
# RESEND_API_KEY
# RESEND_FROM_EMAIL
# NEXTAUTH_URL
# NEXTAUTH_SECRET
# APP_URL
# APP_NAME
